modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="curseofpandora"
version="${file.jarVersion}" #mandatory
displayName="Curse of Pandora" #mandatory
logoFile="curseofpandora.png" #optional
credits="LightLand Team" #optional
authors="lcy0x1" #optional
description='''
This mod is a curios/trinket focused mod that adds a lot of items to strengthen the player and improve game experience.
Player can equip Pandora Necklace and Pandora Bracelet, which can hold 18/9 pandora charms.
The charms will can be edited in the item, or when the holder items are equipped, in the pandora tab.
'''
[[dependencies.curseofpandora]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.23,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="l2complements"
    mandatory=true
    versionRange="[2.4.29,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="l2hostility"
    mandatory=false
    versionRange="[2.4.14,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="l2tabs"
    mandatory=true
    versionRange="[0.2.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.curseofpandora]]
    modId="curios"
    mandatory=true
    versionRange="[5.4.5,)"
    ordering="AFTER"
    side="BOTH"